### ISSUE TITLE
O .env esta versionado com a APP_KEY gerada. 

### ISSUE THREAD

**Issue by Rarfael** [guildatech/api#16]
O correto não seria gerar o .env a partir do .env.example e adicionar o .env no gitignore?

**Comment by schirrel** [comment]
É o correto mesmo Rafael. Se não me engano adicionei ele pensando mais em quando rodar no servidor pois não ter o .env daria problema na hr de subir. Mas também foi um pensamento tolo e nem perguntei pra ninguém heheheh você esta certo
