### ISSUE TITLE
Mudar o nome da branch padrão "Master" para "Main"

### ISSUE THREAD

**Issue by Rarfael** [guildatech/api#19]
Acho que todos estão cientes das discussões envolvendo a associação do nome Master com escravidão, então sugiro a mudança dos nomes das branches Masters em todos os repositórios da Guilda, para Main.
[Github](https://github.com/github/renaming) já esta abandonando a branch master em novos repositórios

**Comment by schirrel** [comment]
Como ja disse no telegram, eu apoio a decisão

**Comment by jcserracampos** [comment]
Solved
