### ISSUE TITLE
Criar cadastro e login de usuários

### ISSUE THREAD

**Issue by jcserracampos** [guildatech/api#6]

**Comment by williamtcastro** [comment]
Cadastro de login deverá conter : 

- Usuário unico
- Senha
- email
- bio
- github

**Comment by williamtcastro** [comment]
Será que deveríamos criar uma tabela de usuários admins ? ou deveríamos incluir direto na tabela de usuário

**Comment by iagocavalcante** [comment]
Creio que admin seria um perfil (outra tabela), mas se não tiver mais que perfil comum e perfil admin, isso pode virar um campo (isAdmin) na tabela usuário.

**Comment by CoderSquirrel** [comment]
Eu iria dar a ideia de ter uma tabela usuario somente com usuario, senha , perfil, email.
Em outra(s) tabela(S) ter os dados de
- git(gitlab, github, bitbucket, outros)
- redes sociais
- informacoes pessoais (data nasciment), cargo, empresa, cidade

O que vocês acham?

**Comment by williamtcastro** [comment]
gostei da ideia do @iagocavalcante para (isAdmin), pq fica mais limpo e mais facil de se lidar, ja a do @CoderSquirrel tbm pode ser implementada
